version: 4.0.0-nightly-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: "# Version number\n$BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER\n$BUILD_SUFFIX = \"nightly\"\n\n# Branch\n$BRANCH = \"$Env:APPVEYOR_REPO_BRANCH\"\n$Env:DOCFX_SOURCE_BRANCH_NAME = \"$BRANCH\"\n\n# Output directory\n$Env:ARTIFACT_DIR = \".\\artifacts\"\n$dir = New-Item -type directory $env:ARTIFACT_DIR\n$dir = $dir.FullName\n\n# Verbosity\nWrite-Host \"Build: $BUILD_NUMBER / Branch: $BRANCH\"\nWrite-Host \"Artifacts will be placed in: $dir\"\n\n# Check if this is a PR\nif (-not $Env:APPVEYOR_PULL_REQUEST_NUMBER)\n{\n    # Rebuild documentation\n    Write-Host \"Commencing complete build\"\n    & .\\rebuild-all.ps1 -ArtifactLocation \"$dir\" -Configuration \"Release\" -VersionSuffix \"$BUILD_SUFFIX\" -BuildNumber $BUILD_NUMBER -DocsPath \".\\docs\" -DocsPackageName \"dsharpplus-docs\"\n}\nelse\n{\n    # Skip documentation\n    Write-Host \"Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER); skipping docs build\"\n    & .\\rebuild-all.ps1 -ArtifactLocation \"$dir\" -Configuration \"Release\" -VersionSuffix \"$BUILD_SUFFIX\" -BuildNumber $BUILD_NUMBER \n}"
artifacts:
- path: artifacts\*.nupkg
- path: artifacts\dsharpplus-docs.tar.xz
deploy:
- provider: NuGet
  server: https://www.myget.org/F/dsharpplus-nightly/api/v2/package
  api_key:
    secure: Zrcd8tC2HncrLbVMK2rD6pcfnS3txk85Enf7Totc4g9sYVMhtHcKVPfOrtFuPW6h
  symbol_server: https://www.myget.org/F/dsharpplus-nightly/symbols/api/v2/package
