language: csharp
mono: none
solution: DSharpPlus.sln

matrix:
  include:
    - dotnet: 1.0.0
    - dotnet: 1.0.1
    - dotnet: 2.0.0

before_install:
  - cp .nuget/NuGet.config ./NuGet.config
script:
  - dotnet restore
  - dotnet publish **/project.csproj
