language: csharp
mono: none
solution: DSharpPlus.sln

git:
  depth: 3
  submodules: false

#matrix: 
#  - DOTNETVER=1.0.0
#  - DOTNETVER=1.0.1
#  - DOTNETVER=2.0.0

dotnet: 2.0.0

env: 
  matrix:
   - COREBTYP=Debug COREAPPTYP=netstandard1.1
   - COREBTYP=Debug COREAPPTYP=netstandard1.3
   - COREBTYP=Debug COREAPPTYP=netstandard2.0
   
   - COREBTYP=Release COREAPPTYP=netstandard1.1
   - COREBTYP=Release COREAPPTYP=netstandard1.3
   - COREBTYP=Release COREAPPTYP=netstandard2.0
   
   - CORESC=--self-contained COREBTYP=Debug COREAPPTYP=netstandard1.1
   - CORESC=--self-contained COREBTYP=Debug COREAPPTYP=netstandard1.3
   - CORESC=--self-contained COREBTYP=Debug COREAPPTYP=netstandard2.0
   
   - CORESC=--self-contained COREBTYP=Release COREAPPTYP=netstandard1.1
   - CORESC=--self-contained COREBTYP=Release COREAPPTYP=netstandard1.3
   - CORESC=--self-contained COREBTYP=Release COREAPPTYP=netstandard2.0

before_install:
  - cp .nuget/NuGet.config ./NuGet.config
script:
  - dotnet restore
  #- dotnet publish **/*.csproj
  
  - bash ./.travis.sh
