language: csharp
mono: none
solution: DSharpPlus.sln

git:
  depth: 3
  submodules: false

#matrix: 
#  - DOTNETVER=1.0.0
#  - DOTNETVER=1.0.1
#  - DOTNETVER=2.0.0

dotnet: 2.0.0

env: 
  matrix:
   - COREBTYP=Debug COREAPPTYP=netcoreapp1.0
   - COREBTYP=Debug COREAPPTYP=netcoreapp1.1
   - COREBTYP=Debug COREAPPTYP=netcoreapp2.0
   - COREBTYP=Debug COREAPPTYP=netstandard1.0
   - COREBTYP=Debug COREAPPTYP=netstandard1.1
   - COREBTYP=Debug COREAPPTYP=netstandard1.2
   - COREBTYP=Debug COREAPPTYP=netstandard1.3
   - COREBTYP=Debug COREAPPTYP=netstandard1.4
   - COREBTYP=Debug COREAPPTYP=netstandard1.5
   - COREBTYP=Debug COREAPPTYP=netstandard1.6
   - COREBTYP=Debug COREAPPTYP=netstandard2.0
   - COREBTYP=Debug COREAPPTYP=net45
   - COREBTYP=Debug COREAPPTYP=net451
   - COREBTYP=Debug COREAPPTYP=net452
   - COREBTYP=Debug COREAPPTYP=net46
   - COREBTYP=Debug COREAPPTYP=net461
   - COREBTYP=Debug COREAPPTYP=net462
   - COREBTYP=Debug COREAPPTYP=net47
   
   - COREBTYP=Release COREAPPTYP=netcoreapp1.0
   - COREBTYP=Release COREAPPTYP=netcoreapp1.1
   - COREBTYP=Release COREAPPTYP=netcoreapp2.0
   - COREBTYP=Release COREAPPTYP=netstandard1.0
   - COREBTYP=Release COREAPPTYP=netstandard1.1
   - COREBTYP=Release COREAPPTYP=netstandard1.2
   - COREBTYP=Release COREAPPTYP=netstandard1.3
   - COREBTYP=Release COREAPPTYP=netstandard1.4
   - COREBTYP=Release COREAPPTYP=netstandard1.5
   - COREBTYP=Release COREAPPTYP=netstandard1.6
   - COREBTYP=Release COREAPPTYP=netstandard2.0
   - COREBTYP=Release COREAPPTYP=net45
   - COREBTYP=Release COREAPPTYP=net451
   - COREBTYP=Release COREAPPTYP=net452
   - COREBTYP=Release COREAPPTYP=net46
   - COREBTYP=Release COREAPPTYP=net461
   - COREBTYP=Release COREAPPTYP=net462
   - COREBTYP=Release COREAPPTYP=net47

before_install:
  - cp .nuget/NuGet.config ./NuGet.config
script:
  - dotnet restore
  #- dotnet publish **/*.csproj
  
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.CommandsNext/DSharpPlus.CommandsNext.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.Interactivity/DSharpPlus.Interactivity.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.Rest/DSharpPlus.Rest.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.Test/DSharpPlus.Test.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.VoiceNext/DSharpPlus.VoiceNext.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.WebSocket.WebSocket4Net/DSharpPlus.WebSocket.WebSocket4Net.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus.WebSocket.WebSocketSharp/DSharpPlus.WebSocket.WebSocketSharp.csproj
  - dotnet publish -f $COREAPPTYP -c $COREBTYP DSharpPlus/DSharpPlus.csproj
