//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSNXT.aResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProj47.aResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average: .
        /// </summary>
        internal static string BenchmarkAverage {
            get {
                return ResourceManager.GetString("BenchmarkAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average: .
        /// </summary>
        internal static string BenchmarkAverageTicker {
            get {
                return ResourceManager.GetString("BenchmarkAverageTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string BenchmarkComma {
            get {
                return ResourceManager.GetString("BenchmarkComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column named &apos;{0}&apos; has wrong data type. It should be {1} when it is {2}..
        /// </summary>
        internal static string Column_named_0_has_wrong_data_type_It_should_be_1_when_it_is_2 {
            get {
                return ResourceManager.GetString("Column_named_0_has_wrong_data_type_It_should_be_1_when_it_is_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column named &apos;{0}&apos; is missing..
        /// </summary>
        internal static string Column_named_0_is_missing {
            get {
                return ResourceManager.GetString("Column_named_0_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count parameter is missing..
        /// </summary>
        internal static string CountParameterMissing {
            get {
                return ResourceManager.GetString("CountParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key size: .
        /// </summary>
        internal static string CryptBytesKeySize {
            get {
                return ResourceManager.GetString("CryptBytesKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing count comparison value expression..
        /// </summary>
        internal static string ErrorExecutingCountComparisonValueExpression {
            get {
                return ResourceManager.GetString("ErrorExecutingCountComparisonValueExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given expression is not a member access chain..
        /// </summary>
        internal static string Extensions_ChainGet_Given_expression_is_not_a_member_access_chain {
            get {
                return ResourceManager.GetString("Extensions_ChainGet_Given_expression_is_not_a_member_access_chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal expression: {0}.
        /// </summary>
        internal static string Illegal_expression_0 {
            get {
                return ResourceManager.GetString("Illegal_expression_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression..
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the supplied expressions is not allowed..
        /// </summary>
        internal static string One_of_the_supplied_expressions_is_not_allowed {
            get {
                return ResourceManager.GetString("One_of_the_supplied_expressions_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the supplied expressions was null..
        /// </summary>
        internal static string One_of_the_supplied_expressions_was_null {
            get {
                return ResourceManager.GetString("One_of_the_supplied_expressions_was_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset size must be &gt;= 0.
        /// </summary>
        internal static string Subset_size_must_be_larger_than_or_equal_to_0 {
            get {
                return ResourceManager.GetString("Subset_size_must_be_larger_than_or_equal_to_0", resourceCulture);
            }
        }
    }
}
