version: 2
jobs:
  build:
    working_directory: ~/DSharpPlus
    docker:
      - image: microsoft/dotnet:2.0.0-sdk-2.0.2-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Restore NuGet packages
          command: dotnet restore -v Minimal
      - run:
          name: Build
          command: dotnet build DSharpPlus.sln -v Minimal -c Release --version-suffix "$CIRCLE_BUILD_NUM"
      - run:
          name: Package
          command: dotnet pack DSharpPlus.sln -v Minimal -c Release -o "$dir" --no-build --version-suffix "$CIRCLE_BUILD_NUM"
