version: 2
jobs:
  build:
    working_directory: ~/DSharpPlus
    docker:
      - image: microsoft/dotnet:2.0.0-sdk-2.0.2-jessie
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: msbuild project
          command: ./build.sh
