var hierarchy =
[
    [ "DSharpPlus.Net.Abstractions.AcknowledgePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_acknowledge_payload.html", null ],
    [ "DSharpPlus.AsyncEvent< T >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ChannelCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ChannelDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ChannelPinsUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ChannelUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ClientErrorEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< DmChannelCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< DmChannelDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildBanAddEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildBanRemoveEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildDownloadCompletedEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildEmojisUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildIntegrationsUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildMemberAddEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildMemberRemoveEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildMembersChunkEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildMemberUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildRoleCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildRoleDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildRoleUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< GuildUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< HeartbeatEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< InviteCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< InviteDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageAcknowledgeEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageBulkDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageCreateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageDeleteEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageReactionAddEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageReactionRemoveEmojiEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageReactionRemoveEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageReactionsClearEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< MessageUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< NodeDisconnectedEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< PlayerUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< PresenceUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< ReadyEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< SocketCloseEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< SocketErrorEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< SocketMessageEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< StatisticsReceivedEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< T >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< TrackExceptionEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< TrackFinishEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< TrackStartEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< TrackStuckEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< TypingStartEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< UnknownEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< UserSettingsUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< UserSpeakingEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< UserUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< VoiceReceiveEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< VoiceServerUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< VoiceStateUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< VoiceUserJoinEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< VoiceUserLeaveEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< WebhooksUpdateEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "DSharpPlus.AsyncEvent< WebSocketCloseEventArgs >", "class_d_sharp_plus_1_1_async_event.html", null ],
    [ "HSNXT.DSharpPlus.Extended.AsyncListeners.AsyncListenerMethod", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_async_listeners_1_1_async_listener_method.html", null ],
    [ "DSharpPlus.AsyncManualResetEvent", "class_d_sharp_plus_1_1_async_manual_reset_event.html", null ],
    [ "Attribute", null, [
      [ "DSharpPlus.PermissionStringAttribute", "class_d_sharp_plus_1_1_permission_string_attribute.html", null ],
      [ "HSNXT.DSharpPlus.CNextNotifier.SuppressErrorAttribute", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_c_next_notifier_1_1_suppress_error_attribute.html", null ],
      [ "HSNXT.DSharpPlus.Extended.AsyncListeners.AsyncListenerAttribute", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_async_listeners_1_1_async_listener_attribute.html", null ],
      [ "HSNXT.DSharpPlus.Extended.SeverityAttribute", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_severity_attribute.html", null ]
    ] ],
    [ "DSharpPlus.VoiceNext.AudioFormat", "struct_d_sharp_plus_1_1_voice_next_1_1_audio_format.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLog", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLogAction", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log_action.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLogActionChange", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log_action_change.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLogActionOptions", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log_action_options.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLogUser", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log_user.html", null ],
    [ "DSharpPlus.Net.Abstractions.AuditLogWebhook", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_audit_log_webhook.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.AwaiterHolder< TMachine, TEventArgs, TContextResult >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_awaiter_holder.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.AwaiterHolder< CancelVerifier, DiscordEventArgs, HSNXT.DSharpPlus.InteractivityNext.InteractivityContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_awaiter_holder.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.AwaiterHolder< HSNXT.DSharpPlus.InteractivityNext.MessageVerifier, MessageCreateEventArgs, HSNXT.DSharpPlus.InteractivityNext.MessageContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_awaiter_holder.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.AwaiterHolder< HSNXT.DSharpPlus.InteractivityNext.ReactionVerifier, MessageReactionAddEventArgs, HSNXT.DSharpPlus.InteractivityNext.ReactionContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_awaiter_holder.html", null ],
    [ "BaseCommandModule", null, [
      [ "DSharpPlus.Test.TestBotCommands", "class_d_sharp_plus_1_1_test_1_1_test_bot_commands.html", null ],
      [ "DSharpPlus.Test.TestBotCommands.Binding", "class_d_sharp_plus_1_1_test_1_1_test_bot_commands_1_1_binding.html", null ],
      [ "DSharpPlus.Test.TestBotDynamicCommands", "class_d_sharp_plus_1_1_test_1_1_test_bot_dynamic_commands.html", null ],
      [ "DSharpPlus.Test.TestBotEvalCommands", "class_d_sharp_plus_1_1_test_1_1_test_bot_eval_commands.html", null ],
      [ "DSharpPlus.Test.TestBotLavaCommands", "class_d_sharp_plus_1_1_test_1_1_test_bot_lava_commands.html", null ],
      [ "DSharpPlus.Test.TestBotVoiceCommands", "class_d_sharp_plus_1_1_test_1_1_test_bot_voice_commands.html", null ]
    ] ],
    [ "DSharpPlus.Net.Models.BaseEditModel", "class_d_sharp_plus_1_1_net_1_1_models_1_1_base_edit_model.html", [
      [ "DSharpPlus.Net.Models.ChannelEditModel", "class_d_sharp_plus_1_1_net_1_1_models_1_1_channel_edit_model.html", null ],
      [ "DSharpPlus.Net.Models.GuildEditModel", "class_d_sharp_plus_1_1_net_1_1_models_1_1_guild_edit_model.html", null ],
      [ "DSharpPlus.Net.Models.MemberEditModel", "class_d_sharp_plus_1_1_net_1_1_models_1_1_member_edit_model.html", null ],
      [ "DSharpPlus.Net.Models.RoleEditModel", "class_d_sharp_plus_1_1_net_1_1_models_1_1_role_edit_model.html", null ]
    ] ],
    [ "BaseExtension", null, [
      [ "HSNXT.DSharpPlus.InteractivityNext.InteractivityExtension", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_interactivity_extension.html", null ]
    ] ],
    [ "DSharpPlus.BaseExtension", "class_d_sharp_plus_1_1_base_extension.html", [
      [ "DSharpPlus.Interactivity.InteractivityExtension", "class_d_sharp_plus_1_1_interactivity_1_1_interactivity_extension.html", null ],
      [ "DSharpPlus.Lavalink.LavalinkExtension", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_extension.html", null ],
      [ "DSharpPlus.VoiceNext.VoiceNextExtension", "class_d_sharp_plus_1_1_voice_next_1_1_voice_next_extension.html", null ],
      [ "HSNXT.DSharpPlus.CNextNotifier.NotifierExtension", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_c_next_notifier_1_1_notifier_extension.html", null ],
      [ "HSNXT.DSharpPlus.Extended.ClientModule< TConfiguration >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_client_module.html", null ],
      [ "HSNXT.DSharpPlus.Extended.ClientModule< TConfiguration >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_client_module.html", null ]
    ] ],
    [ "BaseHelpFormatter", null, [
      [ "DSharpPlus.Test.TestBotHelpFormatter", "class_d_sharp_plus_1_1_test_1_1_test_bot_help_formatter.html", null ]
    ] ],
    [ "DSharpPlus.Net.BaseRestRequest", "class_d_sharp_plus_1_1_net_1_1_base_rest_request.html", [
      [ "DSharpPlus.Net.MultipartWebRequest", "class_d_sharp_plus_1_1_net_1_1_multipart_web_request.html", null ],
      [ "DSharpPlus.Net.RestRequest", "class_d_sharp_plus_1_1_net_1_1_rest_request.html", null ]
    ] ],
    [ "DSharpPlus.Net.Udp.BaseUdpClient", "class_d_sharp_plus_1_1_net_1_1_udp_1_1_base_udp_client.html", [
      [ "DSharpPlus.Net.Udp.DspUdpClient", "class_d_sharp_plus_1_1_net_1_1_udp_1_1_dsp_udp_client.html", null ]
    ] ],
    [ "BinaryReader", null, [
      [ "DSharpPlus.Lavalink.JavaBinaryReader", "class_d_sharp_plus_1_1_lavalink_1_1_java_binary_reader.html", null ]
    ] ],
    [ "CheckBaseAttribute", null, [
      [ "HSNXT.DSharpPlus.Extended.CNext.RequireRoleOrHigherAttribute", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_c_next_1_1_require_role_or_higher_attribute.html", null ]
    ] ],
    [ "HSNXT.DSharpPlus.Extended.ClientModule", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_client_module.html", [
      [ "HSNXT.DSharpPlus.Extended.DspExtended", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_dsp_extended.html", null ]
    ] ],
    [ "DSharpPlus.Net.Abstractions.ClientProperties", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_client_properties.html", null ],
    [ "HSNXT.DSharpPlus.Extended.CommandsNextWrapper", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_commands_next_wrapper.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DiscordUser >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.CollectRequest< T > >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.IPaginationRequest >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.MatchRequest< T > >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.PollEmoji >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.PollRequest >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.Reaction >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< DSharpPlus.Interactivity.EventHandling.ReactionCollectRequest >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityInternals.ConcurrentCollections.ConcurrentHashSet< TMachine >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_internals_1_1_concurrent_collections_1_1_concurrent_hash_set.html", null ],
    [ "DSharpPlus.Net.ConnectionEndpoint", "struct_d_sharp_plus_1_1_net_1_1_connection_endpoint.html", null ],
    [ "DSharpPlus.DebugLogger", "class_d_sharp_plus_1_1_debug_logger.html", null ],
    [ "DefaultContractResolver", null, [
      [ "DSharpPlus.Entities.OptionalJsonContractResolver", "class_d_sharp_plus_1_1_entities_1_1_optional_json_contract_resolver.html", null ]
    ] ],
    [ "DSharpPlus.Entities.DiscordActivity", "class_d_sharp_plus_1_1_entities_1_1_discord_activity.html", null ],
    [ "DSharpPlus.Net.DiscordApiClient", "class_d_sharp_plus_1_1_net_1_1_discord_api_client.html", null ],
    [ "DSharpPlus.Entities.DiscordAsset", "class_d_sharp_plus_1_1_entities_1_1_discord_asset.html", [
      [ "DSharpPlus.Entities.DiscordApplicationAsset", "class_d_sharp_plus_1_1_entities_1_1_discord_application_asset.html", null ],
      [ "DSharpPlus.Entities.DiscordSpotifyAsset", "class_d_sharp_plus_1_1_entities_1_1_discord_spotify_asset.html", null ]
    ] ],
    [ "DSharpPlus.Entities.DiscordBan", "class_d_sharp_plus_1_1_entities_1_1_discord_ban.html", null ],
    [ "DSharpPlus.Entities.DiscordClientStatus", "class_d_sharp_plus_1_1_entities_1_1_discord_client_status.html", null ],
    [ "DSharpPlus.Entities.DiscordColor", "struct_d_sharp_plus_1_1_entities_1_1_discord_color.html", null ],
    [ "DSharpPlus.DiscordConfiguration", "class_d_sharp_plus_1_1_discord_configuration.html", null ],
    [ "DSharpPlus.Entities.DiscordConnection", "class_d_sharp_plus_1_1_entities_1_1_discord_connection.html", null ],
    [ "DSharpPlus.Entities.DiscordCustomStatus", "class_d_sharp_plus_1_1_entities_1_1_discord_custom_status.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbed", "class_d_sharp_plus_1_1_entities_1_1_discord_embed.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedAuthor", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_author.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedBuilder", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_builder.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedField", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_field.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedFooter", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_footer.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedImage", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_image.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedProvider", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_provider.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedThumbnail", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_thumbnail.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedVideo", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_video.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.DiscordEventAwaiter< TEventArgs, TContextResult >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_discord_event_awaiter.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.DiscordEventAwaiter< DiscordEventArgs, InteractivityContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_discord_event_awaiter.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.DiscordEventAwaiter< MessageCreateEventArgs, MessageContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_discord_event_awaiter.html", [
      [ "HSNXT.DSharpPlus.InteractivityNext.MessageVerifier", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_message_verifier.html", null ]
    ] ],
    [ "HSNXT.DSharpPlus.InteractivityNext.DiscordEventAwaiter< MessageReactionAddEventArgs, ReactionContext >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_discord_event_awaiter.html", [
      [ "HSNXT.DSharpPlus.InteractivityNext.ReactionVerifier", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_reaction_verifier.html", null ]
    ] ],
    [ "DSharpPlus.Entities.DiscordGuildEmbed", "class_d_sharp_plus_1_1_entities_1_1_discord_guild_embed.html", null ],
    [ "DSharpPlus.Entities.DiscordInvite", "class_d_sharp_plus_1_1_entities_1_1_discord_invite.html", null ],
    [ "DSharpPlus.Entities.DiscordMentions", "class_d_sharp_plus_1_1_entities_1_1_discord_mentions.html", null ],
    [ "DSharpPlus.Entities.DiscordMessageActivity", "class_d_sharp_plus_1_1_entities_1_1_discord_message_activity.html", null ],
    [ "DSharpPlus.Entities.DiscordMessageReference", "class_d_sharp_plus_1_1_entities_1_1_discord_message_reference.html", null ],
    [ "DSharpPlus.Entities.DiscordOverwriteBuilder", "class_d_sharp_plus_1_1_entities_1_1_discord_overwrite_builder.html", null ],
    [ "DSharpPlus.Entities.DiscordPresence", "class_d_sharp_plus_1_1_entities_1_1_discord_presence.html", null ],
    [ "DSharpPlus.Entities.DiscordReaction", "class_d_sharp_plus_1_1_entities_1_1_discord_reaction.html", null ],
    [ "DSharpPlus.Entities.DiscordRestOverwrite", "struct_d_sharp_plus_1_1_entities_1_1_discord_rest_overwrite.html", null ],
    [ "DSharpPlus.Entities.DiscordRichPresence", "class_d_sharp_plus_1_1_entities_1_1_discord_rich_presence.html", null ],
    [ "DSharpPlus.DiscordShardedClient", "class_d_sharp_plus_1_1_discord_sharded_client.html", null ],
    [ "DSharpPlus.Net.DiscordUri", "class_d_sharp_plus_1_1_net_1_1_discord_uri.html", null ],
    [ "DSharpPlus.Entities.DiscordVoiceRegion", "class_d_sharp_plus_1_1_entities_1_1_discord_voice_region.html", null ],
    [ "DSharpPlus.Entities.DiscordVoiceState", "class_d_sharp_plus_1_1_entities_1_1_discord_voice_state.html", null ],
    [ "DSharpPlus.Entities.DiscordWebhookBuilder", "class_d_sharp_plus_1_1_entities_1_1_discord_webhook_builder.html", null ],
    [ "DSharpPlus.DiscordWebhookClient", "class_d_sharp_plus_1_1_discord_webhook_client.html", null ],
    [ "HSNXT.DSharpPlus.Extended.DspExtendedLogger", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_dsp_extended_logger.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.DuckAuthor", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_duck_author.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.DuckColor", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_duck_color.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.DuckField", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_duck_field.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.DuckFooter", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_duck_footer.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.DuckTimestamp", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_duck_timestamp.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedBuilder.EmbedAuthor", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_builder_1_1_embed_author.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedBuilder.EmbedFooter", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_builder_1_1_embed_footer.html", null ],
    [ "DSharpPlus.Entities.DiscordEmbedBuilder.EmbedThumbnail", "class_d_sharp_plus_1_1_entities_1_1_discord_embed_builder_1_1_embed_thumbnail.html", null ],
    [ "HSNXT.DSharpPlus.Extended.Emoji.Emoji", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_emoji_1_1_emoji.html", null ],
    [ "EventArgs", null, [
      [ "DSharpPlus.AsyncEventArgs", "class_d_sharp_plus_1_1_async_event_args.html", [
        [ "DSharpPlus.EventArgs.DiscordEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_discord_event_args.html", [
          [ "DSharpPlus.EventArgs.ChannelCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_channel_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.ChannelDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_channel_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.ChannelPinsUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_channel_pins_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.ChannelUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_channel_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.ClientErrorEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_client_error_event_args.html", null ],
          [ "DSharpPlus.EventArgs.DmChannelCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_dm_channel_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.DmChannelDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_dm_channel_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildBanAddEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_ban_add_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildBanRemoveEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_ban_remove_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildDownloadCompletedEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_download_completed_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildEmojisUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_emojis_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildIntegrationsUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_integrations_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildMemberAddEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_member_add_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildMemberRemoveEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_member_remove_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildMembersChunkEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_members_chunk_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildMemberUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_member_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildRoleCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_role_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildRoleDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_role_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildRoleUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_role_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.GuildUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_guild_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.HeartbeatEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_heartbeat_event_args.html", null ],
          [ "DSharpPlus.EventArgs.InviteCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_invite_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.InviteDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_invite_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageAcknowledgeEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_acknowledge_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageBulkDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_bulk_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageCreateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_create_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageDeleteEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_delete_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageReactionAddEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_reaction_add_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageReactionRemoveEmojiEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_reaction_remove_emoji_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageReactionRemoveEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_reaction_remove_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageReactionsClearEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_reactions_clear_event_args.html", null ],
          [ "DSharpPlus.EventArgs.MessageUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_message_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.PresenceUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_presence_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.ReadyEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_ready_event_args.html", null ],
          [ "DSharpPlus.EventArgs.SocketCloseEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_socket_close_event_args.html", null ],
          [ "DSharpPlus.EventArgs.SocketErrorEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_socket_error_event_args.html", null ],
          [ "DSharpPlus.EventArgs.TypingStartEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_typing_start_event_args.html", null ],
          [ "DSharpPlus.EventArgs.UnknownEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_unknown_event_args.html", null ],
          [ "DSharpPlus.EventArgs.UserSettingsUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_user_settings_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.UserSpeakingEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_user_speaking_event_args.html", null ],
          [ "DSharpPlus.EventArgs.UserUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_user_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.VoiceServerUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_voice_server_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.VoiceStateUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_voice_state_update_event_args.html", null ],
          [ "DSharpPlus.EventArgs.WebhooksUpdateEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_webhooks_update_event_args.html", null ],
          [ "DSharpPlus.VoiceNext.EventArgs.VoiceReceiveEventArgs", "class_d_sharp_plus_1_1_voice_next_1_1_event_args_1_1_voice_receive_event_args.html", null ],
          [ "DSharpPlus.VoiceNext.EventArgs.VoiceUserJoinEventArgs", "class_d_sharp_plus_1_1_voice_next_1_1_event_args_1_1_voice_user_join_event_args.html", null ],
          [ "DSharpPlus.VoiceNext.EventArgs.VoiceUserLeaveEventArgs", "class_d_sharp_plus_1_1_voice_next_1_1_event_args_1_1_voice_user_leave_event_args.html", null ],
          [ "HSNXT.DSharpPlus.Extended.ExtensionErrorEventArgs", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_extension_error_event_args.html", null ],
          [ "HSNXT.DSharpPlus.Extended.MentionReceivedEventArgs", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_mention_received_event_args.html", null ]
        ] ],
        [ "DSharpPlus.EventArgs.SocketMessageEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_socket_message_event_args.html", [
          [ "DSharpPlus.EventArgs.SocketBinaryMessageEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_socket_binary_message_event_args.html", null ],
          [ "DSharpPlus.EventArgs.SocketTextMessageEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_socket_text_message_event_args.html", null ]
        ] ],
        [ "DSharpPlus.Lavalink.EventArgs.NodeDisconnectedEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_node_disconnected_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.PlayerUpdateEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_player_update_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.StatisticsReceivedEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_statistics_received_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.TrackExceptionEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_exception_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.TrackFinishEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_finish_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.TrackStartEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_start_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.TrackStuckEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_stuck_event_args.html", null ],
        [ "DSharpPlus.Lavalink.EventArgs.WebSocketCloseEventArgs", "class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_web_socket_close_event_args.html", null ]
      ] ],
      [ "DSharpPlus.EventArgs.DebugLogMessageEventArgs", "class_d_sharp_plus_1_1_event_args_1_1_debug_log_message_event_args.html", null ]
    ] ],
    [ "DSharpPlus.Interactivity.EventHandling.EventWaiter< MessageCreateEventArgs >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_event_waiter.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.EventWaiter< MessageReactionAddEventArgs >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_event_waiter.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.EventWaiter< TypingStartEventArgs >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_event_waiter.html", null ],
    [ "Exception", null, [
      [ "DSharpPlus.Exceptions.BadRequestException", "class_d_sharp_plus_1_1_exceptions_1_1_bad_request_exception.html", null ],
      [ "DSharpPlus.Exceptions.NotFoundException", "class_d_sharp_plus_1_1_exceptions_1_1_not_found_exception.html", null ],
      [ "DSharpPlus.Exceptions.RateLimitException", "class_d_sharp_plus_1_1_exceptions_1_1_rate_limit_exception.html", null ],
      [ "DSharpPlus.Exceptions.RequestSizeException", "class_d_sharp_plus_1_1_exceptions_1_1_request_size_exception.html", null ],
      [ "DSharpPlus.Exceptions.UnauthorizedException", "class_d_sharp_plus_1_1_exceptions_1_1_unauthorized_exception.html", null ]
    ] ],
    [ "HSNXT.DSharpPlus.Extended.Expressions", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_expressions.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity.GameParty", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity_1_1_game_party.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity.GameParty.GamePartySize", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity_1_1_game_party_1_1_game_party_size.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity.GameSecrets", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity_1_1_game_secrets.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity.GameTimestamps", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity_1_1_game_timestamps.html", null ],
    [ "DSharpPlus.Net.Abstractions.GatewayHello", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_gateway_hello.html", null ],
    [ "DSharpPlus.Net.Abstractions.GatewayIdentify", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_gateway_identify.html", null ],
    [ "DSharpPlus.Net.Abstractions.GatewayPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_gateway_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.GatewayRequestGuildMembers", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_gateway_request_guild_members.html", null ],
    [ "DSharpPlus.Net.Abstractions.GatewayResume", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_gateway_resume.html", null ],
    [ "ICollection", null, [
      [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< T >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
      [ "DSharpPlus.RingBuffer< T >", "class_d_sharp_plus_1_1_ring_buffer.html", null ],
      [ "HSNXT.DSharpPlus.InteractivityInternals.ConcurrentCollections.ConcurrentHashSet< T >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_internals_1_1_concurrent_collections_1_1_concurrent_hash_set.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "DSharpPlus.BaseDiscordClient", "class_d_sharp_plus_1_1_base_discord_client.html", [
        [ "DSharpPlus.DiscordClient", "class_d_sharp_plus_1_1_discord_client.html", null ],
        [ "DSharpPlus.DiscordRestClient", "class_d_sharp_plus_1_1_discord_rest_client.html", null ]
      ] ],
      [ "DSharpPlus.ImageTool", "class_d_sharp_plus_1_1_image_tool.html", null ],
      [ "DSharpPlus.Interactivity.EventHandling.CollectRequest< T >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_collect_request.html", null ],
      [ "DSharpPlus.Interactivity.EventHandling.EventWaiter< T >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_event_waiter.html", null ],
      [ "DSharpPlus.Interactivity.EventHandling.MatchRequest< T >", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_match_request.html", null ],
      [ "DSharpPlus.Interactivity.EventHandling.ReactionCollector", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_reaction_collector.html", null ],
      [ "DSharpPlus.Interactivity.EventHandling.ReactionCollectRequest", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_reaction_collect_request.html", null ],
      [ "DSharpPlus.Net.WebSocket.IWebSocketClient", "interface_d_sharp_plus_1_1_net_1_1_web_socket_1_1_i_web_socket_client.html", [
        [ "DSharpPlus.Net.WebSocket.WebSocketClient", "class_d_sharp_plus_1_1_net_1_1_web_socket_1_1_web_socket_client.html", null ]
      ] ],
      [ "DSharpPlus.Net.WebSocket.PayloadDecompressor", "class_d_sharp_plus_1_1_net_1_1_web_socket_1_1_payload_decompressor.html", null ],
      [ "DSharpPlus.Net.WebSocket.SocketLock", "class_d_sharp_plus_1_1_net_1_1_web_socket_1_1_socket_lock.html", null ],
      [ "DSharpPlus.VoiceNext.Codec.Opus", "class_d_sharp_plus_1_1_voice_next_1_1_codec_1_1_opus.html", null ],
      [ "DSharpPlus.VoiceNext.Codec.OpusDecoder", "class_d_sharp_plus_1_1_voice_next_1_1_codec_1_1_opus_decoder.html", null ],
      [ "DSharpPlus.VoiceNext.Codec.Rtp", "class_d_sharp_plus_1_1_voice_next_1_1_codec_1_1_rtp.html", null ],
      [ "DSharpPlus.VoiceNext.Codec.Sodium", "class_d_sharp_plus_1_1_voice_next_1_1_codec_1_1_sodium.html", null ],
      [ "DSharpPlus.VoiceNext.Entities.AudioSender", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_audio_sender.html", null ],
      [ "DSharpPlus.VoiceNext.VoiceNextConnection", "class_d_sharp_plus_1_1_voice_next_1_1_voice_next_connection.html", null ],
      [ "HSNXT.DSharpPlus.Extended.DspExtended", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_dsp_extended.html", null ],
      [ "HSNXT.DSharpPlus.Extended.Watchdog", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_watchdog.html", null ],
      [ "HSNXT.DSharpPlus.InteractivityNext.BaseControlState", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_base_control_state.html", [
        [ "HSNXT.DSharpPlus.InteractivityNext.PaginationState", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_pagination_state.html", null ]
      ] ]
    ] ],
    [ "IEnumerable", null, [
      [ "HSNXT.DSharpPlus.InteractivityNext.PaginationEmojis", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_pagination_emojis.html", null ]
    ] ],
    [ "IEqualityComparer", null, [
      [ "DSharpPlus.Lavalink.LavalinkBandAdjustmentComparer", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_band_adjustment_comparer.html", null ],
      [ "HSNXT.DSharpPlus.Extended.ExtensionMethods.SnowflakeEqualityComparer", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_extension_methods_1_1_snowflake_equality_comparer.html", null ]
    ] ],
    [ "IEquatable", null, [
      [ "DSharpPlus.Entities.DiscordApplication", "class_d_sharp_plus_1_1_entities_1_1_discord_application.html", null ],
      [ "DSharpPlus.Entities.DiscordApplicationAsset", "class_d_sharp_plus_1_1_entities_1_1_discord_application_asset.html", null ],
      [ "DSharpPlus.Entities.DiscordChannel", "class_d_sharp_plus_1_1_entities_1_1_discord_channel.html", [
        [ "DSharpPlus.Entities.DiscordDmChannel", "class_d_sharp_plus_1_1_entities_1_1_discord_dm_channel.html", null ]
      ] ],
      [ "DSharpPlus.Entities.DiscordEmoji", "class_d_sharp_plus_1_1_entities_1_1_discord_emoji.html", [
        [ "DSharpPlus.Entities.DiscordGuildEmoji", "class_d_sharp_plus_1_1_entities_1_1_discord_guild_emoji.html", null ]
      ] ],
      [ "DSharpPlus.Entities.DiscordGuild", "class_d_sharp_plus_1_1_entities_1_1_discord_guild.html", null ],
      [ "DSharpPlus.Entities.DiscordMember", "class_d_sharp_plus_1_1_entities_1_1_discord_member.html", null ],
      [ "DSharpPlus.Entities.DiscordMessage", "class_d_sharp_plus_1_1_entities_1_1_discord_message.html", null ],
      [ "DSharpPlus.Entities.DiscordRole", "class_d_sharp_plus_1_1_entities_1_1_discord_role.html", null ],
      [ "DSharpPlus.Entities.DiscordTeam", "class_d_sharp_plus_1_1_entities_1_1_discord_team.html", null ],
      [ "DSharpPlus.Entities.DiscordTeamMember", "class_d_sharp_plus_1_1_entities_1_1_discord_team_member.html", null ],
      [ "DSharpPlus.Entities.DiscordUser", "class_d_sharp_plus_1_1_entities_1_1_discord_user.html", [
        [ "DSharpPlus.Entities.DiscordMember", "class_d_sharp_plus_1_1_entities_1_1_discord_member.html", null ]
      ] ],
      [ "DSharpPlus.Entities.DiscordWebhook", "class_d_sharp_plus_1_1_entities_1_1_discord_webhook.html", null ],
      [ "DSharpPlus.Entities.Optional< T >", "struct_d_sharp_plus_1_1_entities_1_1_optional.html", null ],
      [ "DSharpPlus.Net.RateLimitBucket", "class_d_sharp_plus_1_1_net_1_1_rate_limit_bucket.html", null ]
    ] ],
    [ "IEquatable< Optional< T >>", null, [
      [ "DSharpPlus.Entities.Optional< T >", "struct_d_sharp_plus_1_1_entities_1_1_optional.html", null ]
    ] ],
    [ "IList", null, [
      [ "HSNXT.DSharpPlus.Extended.EmptyList< T >", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_empty_list.html", null ]
    ] ],
    [ "DSharpPlus.Entities.IMention", "interface_d_sharp_plus_1_1_entities_1_1_i_mention.html", [
      [ "DSharpPlus.Entities.EveryoneMention", "struct_d_sharp_plus_1_1_entities_1_1_everyone_mention.html", null ],
      [ "DSharpPlus.Entities.RoleMention", "struct_d_sharp_plus_1_1_entities_1_1_role_mention.html", null ],
      [ "DSharpPlus.Entities.UserMention", "struct_d_sharp_plus_1_1_entities_1_1_user_mention.html", null ]
    ] ],
    [ "DSharpPlus.Interactivity.InteractivityConfiguration", "class_d_sharp_plus_1_1_interactivity_1_1_interactivity_configuration.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.InteractivityConfiguration", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_interactivity_configuration.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.InteractivityContext", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_interactivity_context.html", [
      [ "HSNXT.DSharpPlus.InteractivityNext.MessageContext", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_message_context.html", null ],
      [ "HSNXT.DSharpPlus.InteractivityNext.ReactionContext", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_reaction_context.html", null ]
    ] ],
    [ "DSharpPlus.Interactivity.InteractivityResult< T >", "struct_d_sharp_plus_1_1_interactivity_1_1_interactivity_result.html", null ],
    [ "DSharpPlus.Entities.InternalDiscordMessageReference", "struct_d_sharp_plus_1_1_entities_1_1_internal_discord_message_reference.html", null ],
    [ "DSharpPlus.Net.Abstractions.IOAuth2Payload", "interface_d_sharp_plus_1_1_net_1_1_abstractions_1_1_i_o_auth2_payload.html", [
      [ "DSharpPlus.Net.Abstractions.RestChannelGroupDmRecipientAddPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_group_dm_recipient_add_payload.html", null ],
      [ "DSharpPlus.Net.Abstractions.RestGuildMemberAddPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_member_add_payload.html", null ]
    ] ],
    [ "DSharpPlus.Entities.IOptional", "interface_d_sharp_plus_1_1_entities_1_1_i_optional.html", [
      [ "DSharpPlus.Entities.Optional< T >", "struct_d_sharp_plus_1_1_entities_1_1_optional.html", null ]
    ] ],
    [ "DSharpPlus.Interactivity.EventHandling.IPaginationRequest", "interface_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_i_pagination_request.html", [
      [ "DSharpPlus.Interactivity.EventHandling.PaginationRequest", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_pagination_request.html", null ],
      [ "DSharpPlus.Test.TestBotPaginator", "class_d_sharp_plus_1_1_test_1_1_test_bot_paginator.html", null ]
    ] ],
    [ "DSharpPlus.Net.IpEndpoint", "struct_d_sharp_plus_1_1_net_1_1_ip_endpoint.html", null ],
    [ "IReadOnlyCollection", null, [
      [ "DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet< T >", "class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html", null ],
      [ "DSharpPlus.ReadOnlySet< T >", "struct_d_sharp_plus_1_1_read_only_set.html", null ],
      [ "HSNXT.DSharpPlus.InteractivityInternals.ConcurrentCollections.ConcurrentHashSet< T >", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_internals_1_1_concurrent_collections_1_1_concurrent_hash_set.html", null ]
    ] ],
    [ "IReadOnlyDictionary", null, [
      [ "DSharpPlus.ReadOnlyConcurrentDictionary< TKey, TValue >", "struct_d_sharp_plus_1_1_read_only_concurrent_dictionary.html", null ]
    ] ],
    [ "IReadOnlyList", null, [
      [ "HSNXT.DSharpPlus.Extended.EmptyList< T >", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_empty_list.html", null ]
    ] ],
    [ "DSharpPlus.Net.Abstractions.IReasonAction", "interface_d_sharp_plus_1_1_net_1_1_abstractions_1_1_i_reason_action.html", null ],
    [ "DSharpPlus.VoiceNext.IVoiceFilter", "interface_d_sharp_plus_1_1_voice_next_1_1_i_voice_filter.html", null ],
    [ "JsonConverter", null, [
      [ "DSharpPlus.Entities.OptionalJsonConverter", "class_d_sharp_plus_1_1_entities_1_1_optional_json_converter.html", null ],
      [ "DSharpPlus.Entities.UserStatusConverter", "class_d_sharp_plus_1_1_entities_1_1_user_status_converter.html", null ],
      [ "DSharpPlus.Net.Abstractions.GamePartySizeConverter", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_game_party_size_converter.html", null ],
      [ "DSharpPlus.Net.Abstractions.ShardInfoConverter", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_shard_info_converter.html", null ],
      [ "DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter", "class_d_sharp_plus_1_1_net_1_1_serialization_1_1_snowflake_array_as_dictionary_json_converter.html", null ]
    ] ],
    [ "DSharpPlus.Lavalink.LavalinkBandAdjustment", "struct_d_sharp_plus_1_1_lavalink_1_1_lavalink_band_adjustment.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkConfiguration", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_configuration.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkFailedAddress", "struct_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_failed_address.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkGuildConnection", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_guild_connection.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkIpBlock", "struct_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_ip_block.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkLoadFailedInfo", "struct_d_sharp_plus_1_1_lavalink_1_1_lavalink_load_failed_info.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkLoadResult", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_load_result.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkNodeConnection", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_node_connection.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkPayload", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_payload.html", [
      [ "DSharpPlus.Lavalink.Entities.LavalinkConfigureResume", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_configure_resume.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkDestroy", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_destroy.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkEqualizer", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_equalizer.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkPause", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_pause.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkPlay", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_play.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkPlayPartial", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_play_partial.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkSeek", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_seek.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkStop", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_stop.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkVoiceUpdate", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_voice_update.html", null ],
      [ "DSharpPlus.Lavalink.Entities.LavalinkVolume", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_volume.html", null ]
    ] ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkPlayerState", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_player_state.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkPlaylistInfo", "struct_d_sharp_plus_1_1_lavalink_1_1_lavalink_playlist_info.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkRest", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_rest.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkRouteStatus", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_route_status.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkRouteStatusDetails", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_route_status_details.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkState", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_state.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkStatistics", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_statistics.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkStats", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_stats.html", null ],
    [ "DSharpPlus.Lavalink.LavalinkTrack", "class_d_sharp_plus_1_1_lavalink_1_1_lavalink_track.html", null ],
    [ "DSharpPlus.Lavalink.Entities.LavalinkVoiceServerUpdate", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_lavalink_voice_server_update.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.MebUri", "struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_meb_uri.html", null ],
    [ "HSNXT.DSharpPlus.ModernEmbedBuilder.ModernEmbedBuilder", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_modern_embed_builder_1_1_modern_embed_builder.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.Page", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_page.html", null ],
    [ "DSharpPlus.Interactivity.DSharpPlus.Interactivity.Page", "class_d_sharp_plus_1_1_interactivity_1_1_d_sharp_plus_1_1_interactivity_1_1_page.html", null ],
    [ "DSharpPlus.Interactivity.DSharpPlus.Interactivity.PaginationEmojis", "class_d_sharp_plus_1_1_interactivity_1_1_d_sharp_plus_1_1_interactivity_1_1_pagination_emojis.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.Paginator", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_paginator.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.PollEmoji", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_poll_emoji.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.Poller", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_poller.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.PollRequest", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_poll_request.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity.PresenceAssets", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity_1_1_presence_assets.html", null ],
    [ "DSharpPlus.Test.Program", "class_d_sharp_plus_1_1_test_1_1_program.html", null ],
    [ "DSharpPlus.Entities.PropertyChange< T >", "class_d_sharp_plus_1_1_entities_1_1_property_change.html", null ],
    [ "DSharpPlus.QueryUriBuilder", "class_d_sharp_plus_1_1_query_uri_builder.html", null ],
    [ "DSharpPlus.Interactivity.EventHandling.Reaction", "class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_reaction.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.ReactionCancellationAwaiterHolder", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_reaction_cancellation_awaiter_holder.html", null ],
    [ "HSNXT.DSharpPlus.InteractivityNext.ReactionCollectionContext", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_next_1_1_reaction_collection_context.html", null ],
    [ "DSharpPlus.Net.Abstractions.ReadyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_ready_payload.html", null ],
    [ "HSNXT.DSharpPlus.Extended.ReflectionUtils", "class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_reflection_utils.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_create_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelInviteCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_invite_create_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelMessageBulkDeletePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_message_bulk_delete_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelMessageCreateMultipartPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_message_create_multipart_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelMessageEditPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_message_edit_payload.html", [
      [ "DSharpPlus.Net.Abstractions.RestChannelMessageCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_message_create_payload.html", null ]
    ] ],
    [ "DSharpPlus.Net.Abstractions.RestChannelMessageSuppressEmbedsPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_message_suppress_embeds_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelModifyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_modify_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestChannelPermissionEditPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_channel_permission_edit_payload.html", null ],
    [ "DSharpPlus.Net.RestClient", "class_d_sharp_plus_1_1_net_1_1_rest_client.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildChannelReorderPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_channel_reorder_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_create_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildEmojiModifyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_emoji_modify_payload.html", [
      [ "DSharpPlus.Net.Abstractions.RestGuildEmojiCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_emoji_create_payload.html", null ]
    ] ],
    [ "DSharpPlus.Net.Abstractions.RestGuildIntegrationAttachPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_integration_attach_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildIntegrationModifyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_integration_modify_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildMemberModifyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_member_modify_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildModifyPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_modify_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildPruneResultPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_prune_result_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildRolePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_role_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestGuildRoleReorderPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_guild_role_reorder_payload.html", null ],
    [ "DSharpPlus.Net.RestResponse", "class_d_sharp_plus_1_1_net_1_1_rest_response.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestUserDmCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_user_dm_create_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestUserGroupDmCreatePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_user_group_dm_create_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestUserGuild", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_user_guild.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestUserGuildListPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_user_guild_list_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestUserUpdateCurrentPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_user_update_current_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestWebhookExecutePayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_webhook_execute_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.RestWebhookPayload", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_rest_webhook_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.ShardInfo", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_shard_info.html", null ],
    [ "DSharpPlus.Entities.SnowflakeObject", "class_d_sharp_plus_1_1_entities_1_1_snowflake_object.html", [
      [ "DSharpPlus.Entities.DiscordAttachment", "class_d_sharp_plus_1_1_entities_1_1_discord_attachment.html", null ],
      [ "DSharpPlus.Entities.DiscordAuditLogEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_entry.html", [
        [ "DSharpPlus.Entities.DiscordAuditLogBanEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_ban_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogBotAddEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_bot_add_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogChannelEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_channel_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogEmojiEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_emoji_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogGuildEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_guild_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogIntegrationEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_integration_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogInviteEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_invite_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogKickEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_kick_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogMemberDisconnectEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_member_disconnect_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogMemberMoveEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_member_move_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogMemberUpdateEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_member_update_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogMessageEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_message_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogMessagePinEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_message_pin_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogOverwriteEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_overwrite_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogPruneEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_prune_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogRoleUpdateEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_role_update_entry.html", null ],
        [ "DSharpPlus.Entities.DiscordAuditLogWebhookEntry", "class_d_sharp_plus_1_1_entities_1_1_discord_audit_log_webhook_entry.html", null ]
      ] ],
      [ "DSharpPlus.Entities.DiscordChannel", "class_d_sharp_plus_1_1_entities_1_1_discord_channel.html", null ],
      [ "DSharpPlus.Entities.DiscordEmoji", "class_d_sharp_plus_1_1_entities_1_1_discord_emoji.html", null ],
      [ "DSharpPlus.Entities.DiscordGuild", "class_d_sharp_plus_1_1_entities_1_1_discord_guild.html", null ],
      [ "DSharpPlus.Entities.DiscordGuildPreview", "class_d_sharp_plus_1_1_entities_1_1_discord_guild_preview.html", null ],
      [ "DSharpPlus.Entities.DiscordIntegration", "class_d_sharp_plus_1_1_entities_1_1_discord_integration.html", null ],
      [ "DSharpPlus.Entities.DiscordIntegrationAccount", "class_d_sharp_plus_1_1_entities_1_1_discord_integration_account.html", null ],
      [ "DSharpPlus.Entities.DiscordInviteChannel", "class_d_sharp_plus_1_1_entities_1_1_discord_invite_channel.html", null ],
      [ "DSharpPlus.Entities.DiscordInviteGuild", "class_d_sharp_plus_1_1_entities_1_1_discord_invite_guild.html", null ],
      [ "DSharpPlus.Entities.DiscordMessage", "class_d_sharp_plus_1_1_entities_1_1_discord_message.html", null ],
      [ "DSharpPlus.Entities.DiscordMessageApplication", "class_d_sharp_plus_1_1_entities_1_1_discord_message_application.html", [
        [ "DSharpPlus.Entities.DiscordApplication", "class_d_sharp_plus_1_1_entities_1_1_discord_application.html", null ]
      ] ],
      [ "DSharpPlus.Entities.DiscordOverwrite", "class_d_sharp_plus_1_1_entities_1_1_discord_overwrite.html", null ],
      [ "DSharpPlus.Entities.DiscordRole", "class_d_sharp_plus_1_1_entities_1_1_discord_role.html", null ],
      [ "DSharpPlus.Entities.DiscordTeam", "class_d_sharp_plus_1_1_entities_1_1_discord_team.html", null ],
      [ "DSharpPlus.Entities.DiscordUser", "class_d_sharp_plus_1_1_entities_1_1_discord_user.html", null ],
      [ "DSharpPlus.Entities.DiscordWebhook", "class_d_sharp_plus_1_1_entities_1_1_discord_webhook.html", null ]
    ] ],
    [ "DSharpPlus.Net.Abstractions.StatusUpdate", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_status_update.html", null ],
    [ "Stream", null, [
      [ "DSharpPlus.VoiceNext.VoiceTransmitStream", "class_d_sharp_plus_1_1_voice_next_1_1_voice_transmit_stream.html", null ]
    ] ],
    [ "DSharpPlus.Test.TestBot", "class_d_sharp_plus_1_1_test_1_1_test_bot.html", null ],
    [ "DSharpPlus.Test.TestBotConfig", "class_d_sharp_plus_1_1_test_1_1_test_bot_config.html", null ],
    [ "DSharpPlus.Test.TestFixture1", "class_d_sharp_plus_1_1_test_1_1_test_fixture1.html", null ],
    [ "DSharpPlus.Test.TestFixture2", "class_d_sharp_plus_1_1_test_1_1_test_fixture2.html", null ],
    [ "DSharpPlus.Test.TestFixture3", "class_d_sharp_plus_1_1_test_1_1_test_fixture3.html", null ],
    [ "DSharpPlus.Test.TestJson", "class_d_sharp_plus_1_1_test_1_1_test_json.html", null ],
    [ "DSharpPlus.Test.TestVariables", "class_d_sharp_plus_1_1_test_1_1_test_variables.html", null ],
    [ "DSharpPlus.Lavalink.EventArgs.TrackExceptionData", "struct_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_exception_data.html", null ],
    [ "DSharpPlus.Lavalink.EventArgs.TrackFinishData", "struct_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_finish_data.html", null ],
    [ "DSharpPlus.Lavalink.EventArgs.TrackStuckData", "struct_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_track_stuck_data.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportActivity", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_activity.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportApplication", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_application.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportMember", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_member.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportTeam", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_team.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportTeamMember", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_team_member.html", null ],
    [ "DSharpPlus.Net.Abstractions.TransportUser", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_transport_user.html", null ],
    [ "DSharpPlus.Lavalink.Entities.VoiceDispatch", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_voice_dispatch.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceDispatch", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_dispatch.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceIdentifyPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_identify_payload.html", null ],
    [ "DSharpPlus.VoiceNext.VoiceNextConfiguration", "class_d_sharp_plus_1_1_voice_next_1_1_voice_next_configuration.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoicePacket", "struct_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_packet.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceReadyPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_ready_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceSelectProtocolPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_select_protocol_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceSelectProtocolPayloadData", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_select_protocol_payload_data.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceServerUpdatePayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_server_update_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceSessionDescriptionPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_session_description_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceSpeakingPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_speaking_payload.html", null ],
    [ "DSharpPlus.Net.Abstractions.VoiceStateUpdate", "class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_voice_state_update.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceStateUpdatePayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_state_update_payload.html", null ],
    [ "DSharpPlus.Lavalink.Entities.VoiceStateUpdatePayload", "class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_voice_state_update_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceUserJoinPayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_user_join_payload.html", null ],
    [ "DSharpPlus.VoiceNext.Entities.VoiceUserLeavePayload", "class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_user_leave_payload.html", null ]
];