var namespace_d_sharp_plus_1_1_commands_next_1_1_converters =
[
    [ "ArgumentBindingResult", "struct_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_argument_binding_result.html", "struct_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_argument_binding_result" ],
    [ "BaseHelpFormatter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_base_help_formatter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_base_help_formatter" ],
    [ "BoolConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_bool_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_bool_converter" ],
    [ "DateTimeConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_date_time_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_date_time_converter" ],
    [ "DateTimeOffsetConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_date_time_offset_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_date_time_offset_converter" ],
    [ "DefaultHelpFormatter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_default_help_formatter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_default_help_formatter" ],
    [ "DiscordChannelConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_channel_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_channel_converter" ],
    [ "DiscordColorConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_color_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_color_converter" ],
    [ "DiscordEmojiConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_emoji_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_emoji_converter" ],
    [ "DiscordGuildConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_guild_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_guild_converter" ],
    [ "DiscordMemberConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_member_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_member_converter" ],
    [ "DiscordMessageConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_message_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_message_converter" ],
    [ "DiscordRoleConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_role_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_role_converter" ],
    [ "DiscordUserConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_user_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_discord_user_converter" ],
    [ "EnumConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_enum_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_enum_converter" ],
    [ "Float128Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float128_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float128_converter" ],
    [ "Float32Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float32_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float32_converter" ],
    [ "Float64Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float64_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_float64_converter" ],
    [ "IArgumentConverter", "interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html", null ],
    [ "Int16Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int16_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int16_converter" ],
    [ "Int32Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int32_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int32_converter" ],
    [ "Int64Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int64_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int64_converter" ],
    [ "Int8Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int8_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int8_converter" ],
    [ "NullableConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_nullable_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_nullable_converter" ],
    [ "StringConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_string_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_string_converter" ],
    [ "TimeSpanConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_time_span_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_time_span_converter" ],
    [ "Uint16Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint16_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint16_converter" ],
    [ "Uint32Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint32_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint32_converter" ],
    [ "Uint64Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint64_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint64_converter" ],
    [ "Uint8Converter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint8_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uint8_converter" ],
    [ "UriConverter", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uri_converter.html", "class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_uri_converter" ]
];