var namespace_d_sharp_plus_1_1_commands_next_1_1_attributes =
[
    [ "AliasesAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_aliases_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_aliases_attribute" ],
    [ "CheckBaseAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_check_base_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_check_base_attribute" ],
    [ "CommandAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_command_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_command_attribute" ],
    [ "CommandCooldownBucket", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_command_cooldown_bucket.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_command_cooldown_bucket" ],
    [ "CooldownAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_cooldown_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_cooldown_attribute" ],
    [ "DescriptionAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_description_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_description_attribute" ],
    [ "DontInjectAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_dont_inject_attribute.html", null ],
    [ "GroupAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_group_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_group_attribute" ],
    [ "GroupCommandAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_group_command_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_group_command_attribute" ],
    [ "HiddenAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_hidden_attribute.html", null ],
    [ "ModuleLifespanAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_module_lifespan_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_module_lifespan_attribute" ],
    [ "PriorityAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_priority_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_priority_attribute" ],
    [ "RemainingTextAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_remaining_text_attribute.html", null ],
    [ "RequireBotPermissionsAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_bot_permissions_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_bot_permissions_attribute" ],
    [ "RequireDirectMessageAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_direct_message_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_direct_message_attribute" ],
    [ "RequireGuildAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_guild_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_guild_attribute" ],
    [ "RequireNsfwAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_nsfw_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_nsfw_attribute" ],
    [ "RequireOwnerAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_owner_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_owner_attribute" ],
    [ "RequirePermissionsAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_permissions_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_permissions_attribute" ],
    [ "RequirePrefixesAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_prefixes_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_prefixes_attribute" ],
    [ "RequireRolesAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_roles_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_roles_attribute" ],
    [ "RequireUserPermissionsAttribute", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_user_permissions_attribute.html", "class_d_sharp_plus_1_1_commands_next_1_1_attributes_1_1_require_user_permissions_attribute" ]
];