var searchData=
[
  ['voicedispatch',['VoiceDispatch',['../class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_voice_dispatch.html',1,'DSharpPlus.Lavalink.Entities.VoiceDispatch'],['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_dispatch.html',1,'DSharpPlus.VoiceNext.Entities.VoiceDispatch']]],
  ['voiceidentifypayload',['VoiceIdentifyPayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_identify_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voicenextconfiguration',['VoiceNextConfiguration',['../class_d_sharp_plus_1_1_voice_next_1_1_voice_next_configuration.html',1,'DSharpPlus::VoiceNext']]],
  ['voicenextconnection',['VoiceNextConnection',['../class_d_sharp_plus_1_1_voice_next_1_1_voice_next_connection.html',1,'DSharpPlus::VoiceNext']]],
  ['voicenextextension',['VoiceNextExtension',['../class_d_sharp_plus_1_1_voice_next_1_1_voice_next_extension.html',1,'DSharpPlus::VoiceNext']]],
  ['voicereadypayload',['VoiceReadyPayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_ready_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voicereceiveeventargs',['VoiceReceiveEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_voice_receive_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['voiceselectprotocolpayload',['VoiceSelectProtocolPayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_select_protocol_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voiceselectprotocolpayloaddata',['VoiceSelectProtocolPayloadData',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_select_protocol_payload_data.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voiceserverupdateeventargs',['VoiceServerUpdateEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_voice_server_update_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['voiceserverupdatepayload',['VoiceServerUpdatePayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_server_update_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voicesessiondescriptionpayload',['VoiceSessionDescriptionPayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_session_description_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voicespeakingpayload',['VoiceSpeakingPayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_speaking_payload.html',1,'DSharpPlus::VoiceNext::Entities']]],
  ['voicestateupdate',['VoiceStateUpdate',['../class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_voice_state_update.html',1,'DSharpPlus::Net::Abstractions']]],
  ['voicestateupdateeventargs',['VoiceStateUpdateEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_voice_state_update_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['voicestateupdatepayload',['VoiceStateUpdatePayload',['../class_d_sharp_plus_1_1_lavalink_1_1_entities_1_1_voice_state_update_payload.html',1,'DSharpPlus.Lavalink.Entities.VoiceStateUpdatePayload'],['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_state_update_payload.html',1,'DSharpPlus.VoiceNext.Entities.VoiceStateUpdatePayload']]],
  ['voiceuserleaveeventargs',['VoiceUserLeaveEventArgs',['../class_d_sharp_plus_1_1_voice_next_1_1_event_args_1_1_voice_user_leave_event_args.html',1,'DSharpPlus::VoiceNext::EventArgs']]],
  ['voiceuserleavepayload',['VoiceUserLeavePayload',['../class_d_sharp_plus_1_1_voice_next_1_1_entities_1_1_voice_user_leave_payload.html',1,'DSharpPlus::VoiceNext::Entities']]]
];
