var searchData=
[
  ['channelcreateeventargs',['ChannelCreateEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_channel_create_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['channeldeleteeventargs',['ChannelDeleteEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_channel_delete_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['channeleditmodel',['ChannelEditModel',['../class_d_sharp_plus_1_1_net_1_1_models_1_1_channel_edit_model.html',1,'DSharpPlus::Net::Models']]],
  ['channelpinsupdateeventargs',['ChannelPinsUpdateEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_channel_pins_update_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['channelupdateeventargs',['ChannelUpdateEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_channel_update_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['clienterroreventargs',['ClientErrorEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_client_error_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['clientmodule',['ClientModule',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_client_module.html',1,'HSNXT.DSharpPlus.Extended.ClientModule&lt; TConfiguration &gt;'],['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_client_module.html',1,'HSNXT.DSharpPlus.Extended.ClientModule']]],
  ['clientproperties',['ClientProperties',['../class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_client_properties.html',1,'DSharpPlus::Net::Abstractions']]],
  ['collectrequest',['CollectRequest',['../class_d_sharp_plus_1_1_interactivity_1_1_event_handling_1_1_collect_request.html',1,'DSharpPlus::Interactivity::EventHandling']]],
  ['commandsnextwrapper',['CommandsNextWrapper',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_commands_next_wrapper.html',1,'HSNXT::DSharpPlus::Extended']]],
  ['concurrenthashset',['ConcurrentHashSet',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_internals_1_1_concurrent_collections_1_1_concurrent_hash_set.html',1,'HSNXT.DSharpPlus.InteractivityInternals.ConcurrentCollections.ConcurrentHashSet&lt; T &gt;'],['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus.Interactivity.Concurrency.ConcurrentHashSet&lt; T &gt;']]],
  ['concurrenthashset_3c_20discorduser_20_3e',['ConcurrentHashSet&lt; DiscordUser &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3acollectrequest_3c_20t_20_3e_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::CollectRequest&lt; T &gt; &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3aipaginationrequest_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::IPaginationRequest &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3amatchrequest_3c_20t_20_3e_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::MatchRequest&lt; T &gt; &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3apollemoji_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::PollEmoji &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3apollrequest_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::PollRequest &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3areaction_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::Reaction &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20dsharpplus_3a_3ainteractivity_3a_3aeventhandling_3a_3areactioncollectrequest_20_3e',['ConcurrentHashSet&lt; DSharpPlus::Interactivity::EventHandling::ReactionCollectRequest &gt;',['../class_d_sharp_plus_1_1_interactivity_1_1_concurrency_1_1_concurrent_hash_set.html',1,'DSharpPlus::Interactivity::Concurrency']]],
  ['concurrenthashset_3c_20tmachine_20_3e',['ConcurrentHashSet&lt; TMachine &gt;',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_interactivity_internals_1_1_concurrent_collections_1_1_concurrent_hash_set.html',1,'HSNXT::DSharpPlus::InteractivityInternals::ConcurrentCollections']]],
  ['connectionendpoint',['ConnectionEndpoint',['../struct_d_sharp_plus_1_1_net_1_1_connection_endpoint.html',1,'DSharpPlus::Net']]]
];
