var searchData=
[
  ['severityattribute',['SeverityAttribute',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_severity_attribute.html',1,'HSNXT::DSharpPlus::Extended']]],
  ['shardinfo',['ShardInfo',['../class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_shard_info.html',1,'DSharpPlus::Net::Abstractions']]],
  ['shardinfoconverter',['ShardInfoConverter',['../class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_shard_info_converter.html',1,'DSharpPlus::Net::Abstractions']]],
  ['snowflakearrayasdictionaryjsonconverter',['SnowflakeArrayAsDictionaryJsonConverter',['../class_d_sharp_plus_1_1_net_1_1_serialization_1_1_snowflake_array_as_dictionary_json_converter.html',1,'DSharpPlus::Net::Serialization']]],
  ['snowflakeequalitycomparer',['SnowflakeEqualityComparer',['../struct_h_s_n_x_t_1_1_d_sharp_plus_1_1_extended_1_1_extension_methods_1_1_snowflake_equality_comparer.html',1,'HSNXT::DSharpPlus::Extended::ExtensionMethods']]],
  ['snowflakeobject',['SnowflakeObject',['../class_d_sharp_plus_1_1_entities_1_1_snowflake_object.html',1,'DSharpPlus::Entities']]],
  ['socketbinarymessageeventargs',['SocketBinaryMessageEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_socket_binary_message_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['socketcloseeventargs',['SocketCloseEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_socket_close_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['socketerroreventargs',['SocketErrorEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_socket_error_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['socketlock',['SocketLock',['../class_d_sharp_plus_1_1_net_1_1_web_socket_1_1_socket_lock.html',1,'DSharpPlus::Net::WebSocket']]],
  ['socketmessageeventargs',['SocketMessageEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_socket_message_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['sockettextmessageeventargs',['SocketTextMessageEventArgs',['../class_d_sharp_plus_1_1_event_args_1_1_socket_text_message_event_args.html',1,'DSharpPlus::EventArgs']]],
  ['sodium',['Sodium',['../class_d_sharp_plus_1_1_voice_next_1_1_codec_1_1_sodium.html',1,'DSharpPlus::VoiceNext::Codec']]],
  ['statisticsreceivedeventargs',['StatisticsReceivedEventArgs',['../class_d_sharp_plus_1_1_lavalink_1_1_event_args_1_1_statistics_received_event_args.html',1,'DSharpPlus::Lavalink::EventArgs']]],
  ['statusupdate',['StatusUpdate',['../class_d_sharp_plus_1_1_net_1_1_abstractions_1_1_status_update.html',1,'DSharpPlus::Net::Abstractions']]],
  ['suppresserrorattribute',['SuppressErrorAttribute',['../class_h_s_n_x_t_1_1_d_sharp_plus_1_1_c_next_notifier_1_1_suppress_error_attribute.html',1,'HSNXT::DSharpPlus::CNextNotifier']]]
];
