var searchData=
[
  ['iargumentconverter',['IArgumentConverter',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus.CommandsNext.Converters.IArgumentConverter'],['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus.CommandsNext.Converters.IArgumentConverter&lt; T &gt;']]],
  ['iargumentconverter_3c_20bool_20_3e',['IArgumentConverter&lt; bool &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20byte_20_3e',['IArgumentConverter&lt; byte &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20datetime_20_3e',['IArgumentConverter&lt; DateTime &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20datetimeoffset_20_3e',['IArgumentConverter&lt; DateTimeOffset &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20decimal_20_3e',['IArgumentConverter&lt; decimal &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordchannel_20_3e',['IArgumentConverter&lt; DiscordChannel &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordcolor_20_3e',['IArgumentConverter&lt; DiscordColor &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordemoji_20_3e',['IArgumentConverter&lt; DiscordEmoji &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordguild_20_3e',['IArgumentConverter&lt; DiscordGuild &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordmember_20_3e',['IArgumentConverter&lt; DiscordMember &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordmessage_20_3e',['IArgumentConverter&lt; DiscordMessage &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discordrole_20_3e',['IArgumentConverter&lt; DiscordRole &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20discorduser_20_3e',['IArgumentConverter&lt; DiscordUser &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20double_20_3e',['IArgumentConverter&lt; double &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20float_20_3e',['IArgumentConverter&lt; float &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20int_20_3e',['IArgumentConverter&lt; int &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20long_20_3e',['IArgumentConverter&lt; long &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20sbyte_20_3e',['IArgumentConverter&lt; sbyte &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20short_20_3e',['IArgumentConverter&lt; short &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20string_20_3e',['IArgumentConverter&lt; string &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20t_20_3e',['IArgumentConverter&lt; T &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20timespan_20_3e',['IArgumentConverter&lt; TimeSpan &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20uint_20_3e',['IArgumentConverter&lt; uint &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20ulong_20_3e',['IArgumentConverter&lt; ulong &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20uri_20_3e',['IArgumentConverter&lt; Uri &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['iargumentconverter_3c_20ushort_20_3e',['IArgumentConverter&lt; ushort &gt;',['../interface_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_i_argument_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['icommandmodule',['ICommandModule',['../interface_d_sharp_plus_1_1_commands_next_1_1_entities_1_1_i_command_module.html',1,'DSharpPlus::CommandsNext::Entities']]],
  ['imagetool',['ImageTool',['../class_d_sharp_plus_1_1_image_tool.html',1,'DSharpPlus']]],
  ['implicitgroup',['ImplicitGroup',['../class_d_sharp_plus_1_1_test_1_1_test_bot_commands_1_1_implicit_group.html',1,'DSharpPlus::Test::TestBotCommands']]],
  ['int16converter',['Int16Converter',['../class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int16_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['int32converter',['Int32Converter',['../class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int32_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['int64converter',['Int64Converter',['../class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int64_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['int8converter',['Int8Converter',['../class_d_sharp_plus_1_1_commands_next_1_1_converters_1_1_int8_converter.html',1,'DSharpPlus::CommandsNext::Converters']]],
  ['interactivityconfiguration',['InteractivityConfiguration',['../class_d_sharp_plus_1_1_interactivity_1_1_interactivity_configuration.html',1,'DSharpPlus::Interactivity']]],
  ['interactivitycontext',['InteractivityContext',['../class_d_sharp_plus_1_1_interactivity_1_1_interactivity_context.html',1,'DSharpPlus::Interactivity']]],
  ['interactivityextension',['InteractivityExtension',['../class_d_sharp_plus_1_1_interactivity_1_1_interactivity_extension.html',1,'DSharpPlus::Interactivity']]],
  ['invalidoverloadexception',['InvalidOverloadException',['../class_d_sharp_plus_1_1_commands_next_1_1_exceptions_1_1_invalid_overload_exception.html',1,'DSharpPlus::CommandsNext::Exceptions']]],
  ['ioauth2payload',['IOAuth2Payload',['../interface_d_sharp_plus_1_1_net_1_1_abstractions_1_1_i_o_auth2_payload.html',1,'DSharpPlus::Net::Abstractions']]],
  ['ioptional',['IOptional',['../interface_d_sharp_plus_1_1_entities_1_1_i_optional.html',1,'DSharpPlus::Entities']]],
  ['ipendpoint',['IpEndpoint',['../struct_d_sharp_plus_1_1_net_1_1_ip_endpoint.html',1,'DSharpPlus::Net']]],
  ['ireasonaction',['IReasonAction',['../interface_d_sharp_plus_1_1_net_1_1_abstractions_1_1_i_reason_action.html',1,'DSharpPlus::Net::Abstractions']]],
  ['ivoicefilter',['IVoiceFilter',['../interface_d_sharp_plus_1_1_voice_next_1_1_i_voice_filter.html',1,'DSharpPlus::VoiceNext']]]
];
